# Generated by Django 4.1.7 on 2023-03-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='nome_do_medico',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
